### ISSUE TITLE
When a pod version changed, cached framework wasn't updated

### ISSUE THREAD

**Issue by noodles1024** [Jacky-LinPeng/cocoapods-xlbuild#1]
I ran 'pod update' in my project, some pods were updated, HOWEVER, the new version of pods weren't re-compiled, so prebuilt frameworks are out-dated. This plugin is awesome, please fix this bug.

**Comment by Jacky-LinPeng** [comment]
Thank you for your feedback. At present, you can delete the Pod directory first, and then Pod Install will compile the latest library. I will inform you later when I make corrections

**Comment by Jacky-LinPeng** [comment]
> I ran 'pod update' in my project, some pods were updated, HOWEVER, the new version of pods weren't re-compiled, so prebuilt frameworks are out-dated. This plugin is awesome, please fix this bug.

Please confirm the attention mode of use:
If the project is initially configured as a dynamic library and then changed to a static library, you need to delete the Pod directory and re-install Pod. Otherwise, a Pod version will be updated but not rebuilt

**Comment by Jacky-LinPeng** [comment]
> I ran 'pod update' in my project, some pods were updated, HOWEVER, the new version of pods weren't re-compiled, so prebuilt frameworks are out-dated. This plugin is awesome, please fix this bug.

Please confirm the attention mode of use:
If the project was originally configured as a dynamic library and then changed to a static library, you need to delete the Pod directory and re-execute Pod Install. Otherwise, a Pod version will be updated but not rebuilt

**Comment by Jacky-LinPeng** [comment]
> I ran 'pod update' in my project, some pods were updated, HOWEVER, the new version of pods weren't re-compiled, so prebuilt frameworks are out-dated. This plugin is awesome, please fix this bug.

update cocoapods-xlbuild to 1.1.1
