### ISSUE TITLE
pod file updated, but prebuilt static frameworks weren't updated 

### ISSUE THREAD

**Issue by noodles1024** [Jacky-LinPeng/cocoapods-xlbuild#6]
I was using cocoapods-xlbuild with version 1.1.2, some pods were updated, so I ran 'pod update' command. I found pods were updated, however, prebuilt frameworks were not updated at the same time. When I compiled my project, I got <xxx/y.h> not found error.
It seems that prebuilding occurs before 'pod update'
Following are pieces of log
Prebuild frameworks (total 0)
🤖  Pod Install 

Updating local specs repositories

**Comment by Jacky-LinPeng** [comment]
> I was using cocoapods-xlbuild with version 1.1.2, some pods were updated, so I ran 'pod update' command. I found pods were updated, however, prebuilt frameworks were not updated at the same time. When I compiled my project, I got <xxx/y.h> not found error. It seems that prebuilding occurs before 'pod update' Following are pieces of log Prebuild frameworks (total 0) 🤖 Pod Install
> 
> Updating local specs repositories

Is it convenient to provide podfile pod dependencies

**Comment by noodles1024** [comment]
There is nothing special in podfile except for a private repo. The podfile looks like this:

source 'https://github.com/CocoaPods/Specs.git'
source 'https://xxxx.com/xxx/private_repo_spec.git'

plugin 'cocoapods-xlbuild'
use_frameworks! :linkage => :static
use_static_binary!

#去除三方库警告
install! 'cocoapods', :deterministic_uuids => false
inhibit_all_warnings!
platform :ios, '11.0'
targetsArray = ['AAA']

targetsArray.each do |t|
    target t do
        pod 'Reveal-SDK', '24', :configurations => ['Debug']
        
        pod 'SDWebImage', '~> 5.1.0'
        pod 'MBProgressHUD','~> 1.2.0'
        pod 'FMDB', '~> 2.7.2'
        pod 'FLAnimatedImage', '~> 1.0.12'
        
        #private pod
        pod 'xxx'
        
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    config.build_settings['CODE_SIGN_IDENTITY'] = ''
    end
  end
end

**Comment by Jacky-LinPeng** [comment]
> There is nothing special in podfile except for a private repo. The podfile looks like this:
> 
> source 'https://github.com/CocoaPods/Specs.git' source 'https://xxxx.com/xxx/private_repo_spec.git'
> 
> plugin 'cocoapods-xlbuild' use_frameworks! :linkage => :static use_static_binary!
> 
> #去除三方库警告 install! 'cocoapods', :deterministic_uuids => false inhibit_all_warnings! platform :ios, '11.0' targetsArray = ['AAA']
> 
> targetsArray.each do |t| target t do pod 'Reveal-SDK', '24', :configurations => ['Debug']
> 
> ```
>     pod 'SDWebImage', '~> 5.1.0'
>     pod 'MBProgressHUD','~> 1.2.0'
>     pod 'FMDB', '~> 2.7.2'
>     pod 'FLAnimatedImage', '~> 1.0.12'
>     
>     #private pod
>     pod 'xxx'
>     
> end
> ```
> 
> end
> 
> post_install do |installer| installer.pods_project.targets.each do |target| target.build_configurations.each do |config| config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0' config.build_settings['CODE_SIGN_IDENTITY'] = '' end end end

 你之前说遇到  `<xxx/y.h> not found error` 这个是壳工程导入私有库头文件而报的错误吗？你可以本地先确认一下这个私有库的y.h文件是否存在，然后再确认一下 私有库是否有将y.h设置为`public_header_files `
