### ISSUE TITLE
如果两个库依赖的库有冲突怎么办

### ISSUE THREAD

**Issue by pengzhiqiang110** [Jacky-LinPeng/cocoapods-xlbuild#7]
比如一个库依赖abc，另一个库依赖cde 依赖abc的库要编译，依赖cde的库不要编译，那么c是编译还是不编译

**Comment by Jacky-LinPeng** [comment]
> 比如一个库依赖abc，另一个库依赖cde 依赖abc的库要编译，依赖cde的库不要编译，那么c是编译还是不编译

c会被编译
